name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

env:
  RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:37.20.2@sha256:3633789a934f763d4fcfcf8f94aee68c229c9cdafc5817900c40b51b437af081
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: "/workspace/renovate-bot/renovate-config/config.js" # replace it with your config.js path
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }} # your Revonate bot token
          GITHUB_COM_TOKEN: ${{ secrets.TOKEN_GITHUB_COM }} # your github token

          RENOVATE_ENDPOINT: ${{ github.server_url }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@forgejo.justinelmore.dev>"

          GIT_AUTHOR_NAME: "Renovate Bot"
          GIT_AUTHOR_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
          GIT_COMMITTER_NAME: "Renovate Bot"
          GIT_COMMITTER_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
