name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

env:
  RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG }}

jobs:
  renovate:
    runs-on: docker
    container: ghcr.io/renovatebot/renovate:39.82.9@sha256:06f7e52d7b5109be9ceca95b62ad5cc3c0ecc0948b7ea99f5f98f0630995c094
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: renovate --local
        env:
          RENOVATE_CONFIG_FILE: "/workspace/renovate-bot/renovate-config/config.js" # replace it with your config.js path
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }} # your Revonate bot token
          GITHUB_COM_TOKEN: ${{ secrets.TOKEN_GITHUB_COM }} # your github token

          RENOVATE_ENDPOINT: ${{ github.server_url }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@forgejo.justinelmore.dev>"

          GIT_AUTHOR_NAME: "Renovate Bot"
          GIT_AUTHOR_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
          GIT_COMMITTER_NAME: "Renovate Bot"
          GIT_COMMITTER_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
