name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

env:
  RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.GPG }}

jobs:
  renovate:
    runs-on: ubuntu:latest
    container: ghcr.io/renovatebot/renovate:39.133.3
    steps:
      - uses: actions/checkout@v4
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: "/workspace/renovate-bot/renovate-config/config.js" # replace it with your config.js path
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }} # your Revonate bot token
          GITHUB_COM_TOKEN: ${{ secrets.TOKEN_GITHUB_COM }} # your github token

          ACTION_USER: ${{ secrets.ACTION_USER }}

          RENOVATE_ENDPOINT: ${{ github.server_url }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@forgejo.justinelmore.dev>"

          GIT_AUTHOR_NAME: "Renovate Bot"
          GIT_AUTHOR_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
          GIT_COMMITTER_NAME: "Renovate Bot"
          GIT_COMMITTER_EMAIL: "renovate-bot@forgejo.justinelmore.dev"
